apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mydaemonset
  labels:
     app: nginx
     env: prod
spec:
  selector:
     matchLabels:
       app: nginx
  template:
     metadata:
      name: mydaemonsetpod
      labels:
        app: nginx
     spec:
       containers:
        - name: mydaemonsetcont
          image: lerndevops/tomcat:8.5.47
          ports:
           - containerPort: 8080
