apiVersion: v1
kind: Namespace
metadata:
  name: Tenant-B-100Mi
  labels:
    name: Tenant-B-100Mi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: memory-limit
  namespace: Tenant-B-100Mi
spec:
  hard:
    limits.memory: 100Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: quota-mem
spec:
  containers:
  - name: quota-mem-ctr
    image: nginx
    resources:
      limits:
        memory: 150Mi
